"""Fetch a big pool of *real*, open-licensed meditative instrumental music.

Everything here is downloaded from sources that publish explicit free licenses,
and only tracks whose license is genuinely usable in public (and possibly
monetised) Reels are kept:

    kept      CC0 / Public Domain Mark / PD-old / CC-BY / CC-BY-SA / GFDL
    rejected  anything with -NC (non-commercial) or -ND (no derivatives)

Vocals/chanting are filtered out by keyword, as are clips too short to cut a
45 s window from.  Each kept file is decoded once and re-written as a clean
44.1 kHz stereo WAV under music/library/audio/, and music/library/manifest.json
records the license/attribution of every track so the repo stays auditable.

    python scripts/fetch_music.py --target 240 --dry-run   # see the plan
    python scripts/fetch_music.py --target 240               # actually fetch
    python scripts/fetch_music.py --provider freesound --token-from-env
    python scripts/fetch_music.py --list                     # what we have now

Sources (all verified reachable on 2026-09-10):
  * Freesound  - thousands of CC0 field/studio recordings (tanpura, bansuri,
                 singing bowls, rain).  Originals need a free API token; with
                 none we fall back to the public preview mp3s.
  * archive.org- netlabel releases published whole under CC0/CC-BY, plus a
                 licenseurl search field so filtering is exact, not guessed.
  * Wikimedia Commons - encyclopedic public-domain/CC audio (solo cello, harp,
                 sitar ragas); license comes from each file's extmetadata.
  * music/incoming - your own files; put a LICENSE.txt beside them.

Requires network access (this sandbox has none, CI/GitHub Actions does).
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import subprocess
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import MUSIC, ffmpeg_exe

CURATED = MUSIC / "meditative_music.json"
LIB = MUSIC / "library"
AUDIO = LIB / "audio"
MANIFEST = LIB / "manifest.json"
ATTRIB = Path(__file__).resolve().parents[1] / "ATTRIBUTIONS.md"
UA = "GitaShorts/1.0 (open-music curation; +https://github.com/Megamind2600/solarinvestors)"
AUDIO_EXT = {".mp3", ".wav", ".ogg", ".flac", ".m4a", ".aac", ".aiff", ".aif", ".opus"}
MAX_MB_DEFAULT = 80


def wav_path(rec: dict) -> Path:
    """Absolute path of a library track's normalised WAV."""
    w = rec.get("wav") or ""
    p = Path(w)
    return p if p.is_absolute() else MUSIC / p


# --------------------------------------------------------------------- config
def load_curated() -> dict:
    with open(CURATED, encoding="utf-8") as fh:
        return json.load(fh)


def load_manifest() -> list[dict]:
    if MANIFEST.exists():
        with open(MANIFEST, encoding="utf-8") as fh:
            return json.load(fh)
    return []


def save_manifest(recs: list[dict]) -> None:
    LIB.mkdir(parents=True, exist_ok=True)
    recs = sorted(recs, key=lambda r: (r.get("provider", ""), r["id"]))
    with open(MANIFEST, "w", encoding="utf-8") as fh:
        json.dump(recs, fh, indent=1, ensure_ascii=False)


def write_attributions(recs: list[dict]) -> None:
    """CC-BY/SA need credit; generate the credit list so the licence is honoured."""
    lines = ["# Music attributions", "",
             "Auto-generated by `scripts/fetch_music.py`. Every soundtrack used by the",
             "render pipeline is listed here with its exact licence.", ""]
    by_lic: dict[str, list[dict]] = {}
    for r in recs:
        by_lic.setdefault(r.get("license", "?"), []).append(r)
    for lic in sorted(by_lic):
        lines.append(f"## {lic}")
        lines.append("")
        for r in by_lic[lic]:
            a = r.get("artist") or "unknown"
            t = r.get("title") or r["id"]
            lines.append(f"- **{t}** — {a} — <{r.get('page', r.get('url', ''))}> ({lic})")
        lines.append("")
    ATTRIB.write_text("\n".join(lines), encoding="utf-8")


# ------------------------------------------------------------------ http utils
def http_get(url: str, timeout: int = 60, tries: int = 3) -> bytes:
    last = None
    for i in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA,
                                                       "Accept": "*/*"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.read()
        except Exception as e:                                   # noqa: BLE001
            last = e
            time.sleep(1.5 * (i + 1))
    raise RuntimeError(f"{url}: {last}")


def http_json(url: str, **kw) -> object:
    return json.loads(http_get(url, **kw).decode("utf-8", "replace"))


def tag(s: str) -> str:
    s = re.sub(r"<[^>]+>", " ", s or "")
    return re.sub(r"\s+", " ", html.unescape(s)).strip()


# ---------------------------------------------------------------- license gate
def license_ok(raw: str, cfg: dict) -> tuple[bool, str]:
    """Map any license string a source gives us onto a short id, and say if usable."""
    s = (raw or "").lower().replace(" ", "")
    if not s:
        return False, ""
    for bad in cfg["deny_license_substrings"]:
        if bad.replace(" ", "") in s:
            return False, raw
    if "publicdomain/zero" in s or "cc0" in s or "creativecommons0" in s or s == "cc0":
        return True, "CC0"
    if ("publicdomain" in s or "pd-old" in s or "public-domain" in s
            or s.startswith("pd-") or s in ("pd", "cc-pd", "pdmark", "publicdomainmark")):
        return True, "PublicDomain"
    m = re.search(r"by-sa[-/]?(\d\.?\d?)", s)
    if m:
        return True, f"CC BY-SA {m.group(1) or ''}".strip()
    m = re.search(r"licenses/by/(\d\.\d)", s) or re.search(r"\bby[-/]?(\d\.\d?)", s)
    if m:
        return True, f"CC BY {m.group(1)}"
    if "gfdl" in s:
        return True, "GFDL"
    if "fairuse" in s or "copyright" in s:
        return False, raw
    return False, raw


def text_banned(text: str, cfg: dict) -> bool:
    t = (text or "").lower()
    return any(w in t for w in cfg["deny_words"])


def score(text: str, rec: dict, cfg: dict) -> float:
    t = (text or "").lower()
    s = 3.0 * sum(w in t for w in cfg["prefer_words"])
    s -= 4.0 * sum(w in t for w in cfg["punish_words"])
    d = float(rec.get("duration") or 0)
    if d:                                          # sweet spot: 2 - 8 minutes
        s += 2.0 if 120 <= d <= 480 else (1.0 if d >= 95 else -6.0)
    s += min(3.0, 0.5 * (int(rec.get("downloads", 0) or 0) ** 0.5))
    if rec.get("samplerate", 0) >= 44100:
        s += 1.0
    if rec.get("bitdepth", 0) >= 16:
        s += 0.5
    if rec.get("channels", 2) == 2:
        s += 0.5
    return s


# -------------------------------------------------------------------- providers
def prov_freesound(recipe: dict, cfg: dict, token: str | None, limit: int) -> list[dict]:
    """CC0/CC-BY acoustic recordings. Token -> API originals; no token -> previews."""
    out, seen = [], set()
    for pin in recipe.get("pinned", []):                 # hand-verified seeds
        sid, uid = pin["sid"], pin["uid"]
        title, lic, dur = fs_sound_meta(sid, cfg)
        if title is None:
            print(f"  ! pin fs{sid} rejected (licence {lic or 'unclear'})")
            continue
        seen.add(sid)
        out.append(dict(id=f"fs{sid}", provider="freesound", title=title, artist=f"user {uid}",
                        duration=dur, samplerate=44100, channels=2, downloads=0,
                        url=f"https://cdn.freesound.org/previews/{sid // 1000}/{sid}_{uid}-hq.mp3",
                        page=f"https://freesound.org/s/{sid}/", license=lic,
                        tags=recipe["tags"] + [pin.get("why", "")], mood=recipe.get("mood"),
                        recipe=recipe["name"], pinned=True))
    for q in recipe.get("queries", []):
        extra = recipe.get("filters", "")
        if token:
            flt = 'license:"Creative Commons 0" ' + extra
            params = {"query": q, "filter": flt.strip(), "fields":
                      "id,name,username,date,description,tags,license,duration,"
                      "bitdepth,samplerate,channels,num_downloads,previews,download,url",
                      "page_size": 30, "order_by": "num_downloads desc"}
            url = "https://freesound.org/apiv2/search/text/?" + urllib.parse.urlencode(params)
            try:
                data = http_json(url + f"&token={token}")
            except Exception as e:                                # noqa: BLE001
                print(f"  freesound api failed ({e}); falling back to scraping")
                data = None
            for it in (data or {}).get("results", []):
                ok, lic = license_ok(str(it.get("license", "")), cfg)
                if not ok or text_banned(it.get("name", "") + " " + it.get("description", ""), cfg):
                    continue
                pv = (it.get("previews") or {}).get("preview-hq-mp3") or \
                     (it.get("previews") or {}).get("preview-lq-mp3")
                dl = it.get("download") or pv
                if not dl or it["id"] in seen:
                    continue
                seen.add(it["id"])
                out.append(dict(id=f"fs{it['id']}", provider="freesound", title=it["name"],
                                artist=it.get("username"), duration=it.get("duration"),
                                samplerate=it.get("samplerate"), bitdepth=it.get("bitdepth"),
                                channels=it.get("channels"), downloads=it.get("num_downloads"),
                                url=dl + f"?token={token}", page=it.get("url"),
                                license=lic, tags=recipe["tags"], mood=recipe.get("mood"),
                                recipe=recipe["name"]))
        else:
            qurl = ("https://freesound.org/search/?" +
                    urllib.parse.urlencode({"q": q, "f": 'license:"Creative Commons 0" ' + extra}))
            try:
                page = http_get(qurl).decode("utf-8", "replace")
            except Exception as e:                                # noqa: BLE001
                print(f"  freesound scrape failed: {e}")
                continue
            # The waveform thumbnail encodes sound id + uploader id, which is all
            # the public preview CDN needs:  /previews/<id//1000>/<id>_<uid>-hq.mp3
            ids = []
            for m in re.finditer(r"cdn\.freesound\.org/displays/(\d+)/(\d+)_(\d+)_wave", page):
                sid, uid = int(m.group(2)), m.group(3)
                if sid not in seen and 0 < sid < 10_000_000:
                    seen.add(sid)
                    ids.append((sid, uid))
            for sid, uid in ids[: limit * 2]:
                pv = f"https://cdn.freesound.org/previews/{sid // 1000}/{sid}_{uid}-hq.mp3"
                title, lic, dur = fs_sound_meta(sid, cfg)
                if title is None or text_banned(title, cfg):
                    continue
                out.append(dict(id=f"fs{sid}", provider="freesound", title=title,
                                artist=f"freesound user {uid}", duration=dur,
                                samplerate=44100, channels=2, downloads=0,
                                url=pv, page=f"https://freesound.org/s/{sid}/",
                                license=lic, tags=recipe["tags"], mood=recipe.get("mood"),
                                recipe=recipe["name"], preview_only=True))
                if len(out) >= limit:
                    break
        if len(out) >= limit:
            break
        time.sleep(0.4)
    return out[:limit]


def fs_sound_meta(sid: int, cfg: dict) -> tuple[str | None, str, float]:
    """Read title + exact licence from the sound page (also confirms it is free)."""
    try:
        h = http_get(f"https://freesound.org/s/{sid}/").decode("utf-8", "replace")
    except Exception:                                             # noqa: BLE001
        return None, "", 0.0
    m = re.search(r"<title>\s*Freesound\s*-\s*(.+?)\s*</title>", h, re.S)
    title = tag(m.group(1)) if m else f"freesound {sid}"
    lm = (re.search(r"creativecommons\.org/licenses/([a-z-]+)/([0-9.]+)/", h) or
          re.search(r"creativecommons\.org/publicdomain/(zero|mark)/", h))
    raw = lm.group(0) if lm else ""
    ok, lic = license_ok(raw, cfg)
    if not ok:
        return None, "", 0.0
    dm = re.search(r"Duration[^0-9]{0,80}?(?:</dt>\s*<dd>)?(\d+):(\d\d)(?:\.(\d+))?", h, re.S)
    dur = int(dm.group(1)) * 60 + int(dm.group(2)) + (int(dm.group(3) or 0) / 100 if dm.group(3) else 0) \
        if dm else 0.0
    return title, lic, dur


def prov_archive(recipe: dict, cfg: dict, limit: int) -> list[dict]:
    """Netlabel albums with an explicit licenseurl -> exact licence filtering."""
    out, seen = [], set()
    for q in recipe["queries"]:
        params = {"q": q, "fl[]": ["identifier", "title", "creator", "downloads",
                                    "licenseurl", "year"],
                  "rows": 40, "page": 1, "output": "json",
                  "sort[]": recipe.get("sort", "downloads desc")}
        url = "https://archive.org/advancedsearch.php?" + urllib.parse.urlencode(params, doseq=True)
        try:
            docs = http_json(url)["response"]["docs"]
        except Exception as e:                                    # noqa: BLE001
            print(f"  archive search failed: {e}")
            continue
        for d in docs:
            ok, lic = license_ok(d.get("licenseurl", ""), cfg)
            title = " ".join(d.get("title") or []) if isinstance(d.get("title"), list) else d.get("title", "")
            if not ok or text_banned(title, cfg) or d["identifier"] in seen:
                continue
            seen.add(d["identifier"])
            # which files does the item actually serve?
            try:
                meta = http_json(f"https://archive.org/metadata/{d['identifier']}")
            except Exception:                                     # noqa: BLE001
                continue
            for f in meta.get("files", []):
                nm = f.get("name", "")
                if Path(nm).suffix.lower() not in AUDIO_EXT or f.get("source") == "metadata":
                    continue
                if text_banned(nm, cfg):
                    continue
                size_mb = (f.get("size") or 0) / 1e6
                if not 0.3 <= size_mb <= MAX_MB_DEFAULT:
                    continue
                try:
                    dur = float(str(f.get("length", "0")).split(":")[0]) * 60 + \
                          float(str(f.get("length", "0")).split(":")[-1])
                except Exception:                                 # noqa: BLE001
                    dur = 0.0
                if dur and dur < cfg["min_duration"]:
                    continue
                out.append(dict(id=f"ia{d['identifier']}-{Path(nm).stem}"[:110],
                                provider="archive", title=tag(f.get("title") or Path(nm).stem),
                                artist=tag(" ".join(meta.get("metadata", {}).get("creator", [""])))
                                     or d.get("creator") or title,
                                duration=dur, downloads=d.get("downloads", 0),
                                url="https://archive.org/download/%s/%s" % (d["identifier"],
                                                                             urllib.parse.quote(nm)),
                                page=f"https://archive.org/details/{d['identifier']}",
                                license=lic, tags=recipe["tags"], mood=recipe.get("mood"),
                                recipe=recipe["name"]))
                if len(out) >= limit:
                    return out
            time.sleep(0.3)
    return out[:limit]


def prov_commons(recipe: dict, cfg: dict, limit: int) -> list[dict]:
    """MediaWiki API: license + artist come from each file's own metadata."""
    out, seen = [], set()
    for q in recipe["queries"]:
        params = {"action": "query", "format": "json", "generator": "search",
                  "gsrsearch": q, "gsrnamespace": 6, "gsrlimit": 30,
                  "prop": "imageinfo",
                  "iiprop": "url|size|mime|extmetadata"}
        url = "https://commons.wikimedia.org/w/api.php?" + urllib.parse.urlencode(params)
        try:
            pages = http_json(url).get("query", {}).get("pages", {})
        except Exception as e:                                    # noqa: BLE001
            print(f"  commons search failed: {e}")
            continue
        for p in pages.values():
            info = (p.get("imageinfo") or [{}])[0]
            if not str(info.get("mime", "")).startswith("audio"):
                continue
            em = info.get("extmetadata", {})
            raw = (em.get("License", {}).get("value", "") or
                   em.get("LicenseShortName", {}).get("value", "") or
                   em.get("LicenseUrl", {}).get("value", ""))
            ok, lic = license_ok(raw, cfg)
            title = p.get("title", "")
            if not ok or text_banned(title, cfg) or title in seen:
                continue
            if info.get("size", 0) / 1e6 > MAX_MB_DEFAULT:
                continue
            seen.add(title)
            out.append(dict(id="wc" + hashlib.sha1(title.encode()).hexdigest()[:12],
                            provider="commons", title=tag(title.replace("File:", "")),
                            artist=tag(em.get("Artist", {}).get("value", "")),
                            duration=0, url=info.get("url"),
                            page="https://commons.wikimedia.org/wiki/" +
                                 urllib.parse.quote(title.replace(" ", "_")),
                            license=lic, tags=recipe["tags"], mood=recipe.get("mood"),
                            recipe=recipe["name"]))
        if len(out) >= limit:
            break
        time.sleep(0.4)
    return out[:limit]


def prov_local(recipe: dict, cfg: dict, limit: int) -> list[dict]:
    root = Path(recipe["queries"][0])
    if not root.exists():
        return []
    out = []
    for f in sorted(root.rglob("*")):
        if f.suffix.lower() not in AUDIO_EXT or f.stat().st_size < 200_000:
            continue
        lic = "Local/unset"
        side = f.with_suffix(".LICENSE.txt")
        if side.exists():
            ok, lic = license_ok(side.read_text()[:400], cfg)
            if not ok:
                print(f"  skipping {f.name}: licence not usable for public reels ({lic})")
                continue
        elif "local" not in recipe["name"]:
            continue
        out.append(dict(id="loc" + f.stem.replace(" ", "_")[:60], provider="local",
                        title=f.stem, artist="local", duration=0, url=str(f),
                        license=lic, tags=recipe["tags"], mood=recipe.get("mood"),
                        recipe=recipe["name"]))
        if len(out) >= limit:
            break
    return out


# ------------------------------------------------------------ decode + normalize
def probe(path: Path) -> dict:
    """Duration / rate / channels via ffmpeg (the pip wheel ships no ffprobe)."""
    try:
        p = subprocess.run([ffmpeg_exe(), "-i", str(path)], capture_output=True, text=True)
        err = p.stderr
        m = re.search(r"Duration:\s*(\d+):(\d\d):([\d.]+)", err)
        if m:
            dur = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3))
        sr = int(re.search(r"(\d+) Hz", err).group(1)) if re.search(r"(\d+) Hz", err) else 0
        ch = int(re.search(r"(\d+) (?:audio )?channels", err).group(1)) \
            if re.search(r"(\d+) (?:audio )?channels", err) else 2
        return {"duration": round(dur, 2), "samplerate": sr, "channels": ch}
    except Exception:                                             # noqa: BLE001
        return {"duration": 0, "samplerate": 0, "channels": 2}


def to_wav(src: Path, dst: Path) -> bool:
    dst.parent.mkdir(parents=True, exist_ok=True)
    cmd = [ffmpeg_exe(), "-y", "-loglevel", "error", "-i", str(src),
           "-vn", "-ac", "2", "-ar", "44100", "-sample_fmt", "s16",
           "-af", "highpass=f=28", str(dst)]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
        return dst.exists() and dst.stat().st_size > 200_000
    except subprocess.CalledProcessError:
        return False


# ---------------------------------------------------------------------- driver
def main():
    global MAX_MB_DEFAULT
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", type=int, default=240,
                    help="total tracks to keep across all recipes (701 unique beds "
                         "would give every shloka its own track)")
    ap.add_argument("--provider", default=None, help="restrict to one provider")
    ap.add_argument("--recipe", default=None, help="restrict to one recipe name")
    ap.add_argument("--per-query", type=int, default=30)
    ap.add_argument("--min-duration", type=float, default=None)
    ap.add_argument("--max-mb", type=float, default=MAX_MB_DEFAULT)
    ap.add_argument("--token-from-env", action="store_true",
                    help="use $FREESOUND_TOKEN for API access (original WAVs, not previews)")
    ap.add_argument("--dry-run", action="store_true", help="resolve + report, no download")
    ap.add_argument("--list", action="store_true", help="print the current library")
    ap.add_argument("--check", action="store_true", help="verify every manifest entry decodes")
    args = ap.parse_args()

    MAX_MB_DEFAULT = args.max_mb

    cfg = load_curated()
    if args.min_duration:
        cfg["filters"]["min_duration"] = args.min_duration
    cfg["filters"]["min_duration"] = float(cfg["filters"].get("min_duration", 95))

    if args.list:
        recs = load_manifest()
        print(f"library: {len(recs)} tracks")
        for r in recs[: args.target if args.target else 40]:
            print(f"  {r['id']:<44} {r.get('license',''):<14} "
                  f"{r.get('duration',0):7.1f}s  {r.get('title','')[:44]}")
        return

    if args.check:
        bad = 0
        for r in load_manifest():
            p = MUSIC / r["wav"]
            if not p.exists() or not probe(p)["duration"]:
                print("MISSING/undecodable:", r["id"], p)
                bad += 1
        print("check:", "all good" if not bad else f"{bad} broken")
        return

    token = os.environ.get("FREESOUND_TOKEN") if args.token_from_env else None
    if args.token_from_env and not token:
        sys.exit("FREESOUND_TOKEN is empty - create a free app at "
                 "freesound.org/help/faq/#api and export FREESOUND_TOKEN=...")

    candidates: list[dict] = []
    for recipe in cfg["recipes"]:
        if args.provider and recipe["provider"] != args.provider:
            continue
        if args.recipe and recipe["name"] != args.recipe:
            continue
        print(f"[{recipe['provider']}] {recipe['name']}: {recipe['note']}")
        lim = max(args.per_query, recipe.get("target", 20))
        prov = recipe["provider"]
        try:
            if prov == "freesound":
                got = prov_freesound(recipe, cfg["filters"], token, lim)
            elif prov == "archive":
                got = prov_archive(recipe, cfg["filters"], lim)
            elif prov == "commons":
                got = prov_commons(recipe, cfg["filters"], lim)
            elif prov == "local":
                got = prov_local(recipe, cfg["filters"], lim)
            else:
                print("  unknown provider", prov)
                got = []
        except Exception as e:                                    # noqa: BLE001
            print("  provider error:", e)
            got = []
        for g in got:
            g["score"] = round(score(f"{g.get('title','')} {g.get('mood','')} "
                                     f"{' '.join(g.get('tags',[]))}", g, cfg["filters"]), 2)
        got.sort(key=lambda g: -g["score"])
        print(f"  -> {len(got)} licence-clean candidates (top score {got[0]['score'] if got else '-'})")
        candidates += got[: recipe.get("target", 20)]

    # de-duplicate across recipes, rank globally, cut to --target
    have = {r["id"]: r for r in load_manifest()}
    uniq: dict[str, dict] = {}
    for c in sorted(candidates, key=lambda c: -c.get("score", 0)):
        key = c["id"]
        if key not in uniq:
            uniq[key] = c
    picked = list(uniq.values())[: args.target]
    print(f"\npool: {len(picked)} unique tracks (target {args.target})")

    if args.dry_run:
        for c in picked:
            print(f"  {c['provider']:<9} {c['license']:<12} {c.get('duration',0):7.1f}s "
                  f"s{c['score']:>6}  {c['title'][:50]}  {c['url'][:70]}")
        return

    tmp = Path("/tmp/gita_music")
    tmp.mkdir(parents=True, exist_ok=True)
    new = 0
    for c in picked:
        wid = c["id"]
        wav = AUDIO / f"{wid}.wav"
        if wav.exists() and probe(wav)["duration"] >= cfg["filters"]["min_duration"]:
            c["wav"] = str(wav.relative_to(MUSIC))
            c["bytes"] = wav.stat().st_size
            have[wid] = {**have.get(wid, {}), **c}
            continue
        raw = tmp / (wid + ".bin")
        try:
            if c["provider"] == "local":
                src = Path(c["url"])
            else:
                data = http_get(c["url"], timeout=180)
                src = raw
                src.write_bytes(data)
            if not to_wav(src, wav):
                print("  ! decode failed:", wid)
                continue
            info = probe(wav)
            if info["duration"] < cfg["filters"]["min_duration"]:
                print(f"  - too short ({info['duration']:.0f}s):", wid)
                wav.unlink(missing_ok=True)
                continue
            c.update(wav=str(wav.relative_to(MUSIC)), **{k: v for k, v in info.items() if v})
            c["sha1"] = hashlib.sha1(wav.read_bytes()).hexdigest()[:16]
            c["bytes"] = wav.stat().st_size
            have[wid] = c
            new += 1
            print(f"  + {wid[:40]:<40} {info['duration']:7.1f}s  {c['title'][:44]}")
        except Exception as e:                                    # noqa: BLE001
            print("  ! fetch failed:", wid, str(e)[:120])
        finally:
            if raw.exists():
                raw.unlink(missing_ok=True)

    recs = [r for r in have.values() if Path(MUSIC / r["wav"]).exists()]
    save_manifest(recs)
    write_attributions(recs)
    print(f"\nadded {new}; library now {len(recs)} tracks -> {MANIFEST}")
    if new == 0:
        print("nothing added - this needs network access; run it locally or in CI.")


if __name__ == "__main__":
    main()
